#!/usr/bin/env python


import rospy
import math
from sensor_msgs.msg import Range
from std_msgs.msg import String

def stream(data):
	pub=rospy.Publisher('chatter', String, queue_size=10)

	rate = rospy.Rate(10)
	while not rospy.is_shutdown():
		hello_str = data.range
        	rospy.loginfo(hello_str)
        	pub.publish(hello_str)
        	rate.sleep()
		

def streamer():
	rospy.init_node('streamer', anonymous=True)

	rospy.Subscriber("atilay/sonar", Range, stream)

	rospy.spin()

if __name__ == '__main__':
    try:
        streamer()
    except rospy.ROSInterruptException:
        pass
